'use client'

import { useState } from 'react'
import { ArrowUpRight, ChevronDown, HardHat, MapPin, Menu, MessageCircle, ShieldCheck, Users, X } from 'lucide-react'
import { trainingCategories, trainingForCity, trainingByCategory, type TrainingCategory } from '@/data/trainings'
import { PHONE_DISPLAY, whatsappLink as createWhatsappLink } from '@/lib/constants'

const DEFAULT_CITY = 'Bandung'
const faqs = [
  ['Apakah sertifikat pelatihan diakui secara resmi?', 'Kami membantu memilih program dan skema sertifikasi yang sesuai dengan kebutuhan kompetensi serta ketentuan yang berlaku.'],
  ['Apakah tersedia in-house training?', 'Tersedia di lokasi perusahaan atau tempat yang disepakati, dengan materi dan jadwal yang disesuaikan.'],
  ['Apakah tersedia pelatihan online atau hybrid?', 'Beberapa program dapat dilakukan secara online atau hybrid sesuai jenis pelatihannya.'],
  ['Bagaimana cara mendaftar?', 'Klik tombol WhatsApp, sampaikan program dan jumlah peserta, lalu tim kami akan mengirimkan jadwal.'],
]

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) {
  return <div className="mb-10 max-w-2xl"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">{eyebrow}</p><h2 className="text-balance text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">{title}</h2>{description && <p className="mt-4 text-pretty leading-7 text-muted-foreground">{description}</p>}</div>
}

export default function Page({ city = DEFAULT_CITY, citySlug, locationName }: { city?: string; citySlug?: string; locationName?: string }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const serviceLocation = locationName ?? city
  const articlePath = `/${citySlug ?? city.toLowerCase().replace(/\s+/g, '-').replace(/^kota-/, '')}/artikel`
  const [activeFaq, setActiveFaq] = useState<number | null>(0)
  const [category, setCategory] = useState<TrainingCategory>('Pelatihan')
  const visibleTrainings = trainingByCategory(category)
  const whatsappLink = (message = `Halo, saya ingin bertanya tentang pelatihan K3 di ${serviceLocation}.`) => createWhatsappLink(message)

  return <main className="min-h-screen overflow-x-hidden bg-background text-foreground">
    <header className="sticky top-0 z-50 border-b border-border/80 bg-background/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#beranda" className="flex items-center gap-2 font-semibold"><span className="flex size-8 items-center justify-center rounded-md bg-primary text-primary-foreground"><HardHat size={17} /></span>Training Sertifikasi</a><nav className="hidden gap-7 text-sm text-muted-foreground md:flex"><a href="#beranda">Beranda</a><a href="#pelatihan">Pelatihan</a><a href={articlePath}>Artikel</a><a href="#kontak">Kontak</a></nav><a href={whatsappLink()} target="_blank" rel="noreferrer" className="hidden rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground sm:block">Hubungi Kami</a><button aria-label={menuOpen ? 'Tutup menu' : 'Buka menu'} onClick={() => setMenuOpen(!menuOpen)} className="rounded-md p-2 md:hidden">{menuOpen ? <X size={21} /> : <Menu size={21} />}</button></div>{menuOpen && <nav className="border-t border-border bg-background px-5 py-4 md:hidden"><div className="flex flex-col gap-4 text-sm"><a href="#beranda" onClick={() => setMenuOpen(false)}>Beranda</a><a href="#pelatihan" onClick={() => setMenuOpen(false)}>Pelatihan</a><a href={articlePath} onClick={() => setMenuOpen(false)}>Artikel</a><a href="#kontak" onClick={() => setMenuOpen(false)}>Kontak</a><a href={whatsappLink()} target="_blank" rel="noreferrer" className="rounded-lg bg-primary px-4 py-3 text-center font-medium text-primary-foreground">Hubungi Kami</a></div></nav>}</header>

    <section id="beranda" className="border-b border-border px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.1fr_0.9fr] lg:gap-24"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-border px-3 py-1.5 text-xs font-medium text-muted-foreground"><span className="size-1.5 rounded-full bg-emerald-600" /> Pelatihan K3 profesional di {serviceLocation}</div><h1 className="max-w-3xl text-balance text-5xl font-semibold leading-[1.05] tracking-[-0.065em] sm:text-6xl lg:text-7xl">Bangun tempat kerja yang <span className="text-muted-foreground">lebih aman.</span></h1><p className="mt-7 max-w-xl text-pretty leading-7 text-muted-foreground sm:text-lg">Pelatihan dan sertifikasi K3 yang relevan untuk individu maupun perusahaan di {city} dan sekitarnya.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={whatsappLink()} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-5 py-3.5 text-sm font-medium text-primary-foreground">Konsultasi via WhatsApp <ArrowUpRight size={16} /></a><a href="#pelatihan" className="inline-flex items-center justify-center rounded-lg border border-border px-5 py-3.5 text-sm font-medium">Lihat Daftar Pelatihan</a></div><div className="mt-12 grid max-w-xl grid-cols-3 gap-5 border-t border-border pt-6"><div><p className="text-xl font-semibold sm:text-2xl">500+</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Perusahaan terlayani</p></div><div><p className="text-xl font-semibold sm:text-2xl">200+</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Kota layanan</p></div><div><p className="text-xl font-semibold sm:text-2xl">Resmi</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Program tersertifikasi</p></div></div></div><div className="rounded-2xl border border-border bg-secondary/40 p-6 sm:p-8"><p className="text-sm text-muted-foreground">Fokus utama kami</p><p className="mt-4 max-w-xs text-3xl font-semibold tracking-[-0.05em]">Kompetensi yang berdampak nyata.</p><div className="mt-16 grid grid-cols-2 gap-3"><div className="rounded-xl border border-border bg-background p-4"><ShieldCheck size={19} /><p className="mt-8 text-sm font-medium">Kompetensi</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Materi terstruktur</p></div><div className="rounded-xl border border-border bg-background p-4"><Users size={19} /><p className="mt-8 text-sm font-medium">Perusahaan</p><p className="mt-1 text-xs leading-5 text-muted-foreground">In-house fleksibel</p></div></div></div></div></section>

    <section id="pelatihan" className="border-b border-border bg-secondary/35 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Katalog program" title={`Program K3 untuk ${serviceLocation}.`} description="Pilih kategori untuk melihat seluruh program yang tersedia." /><div className="mb-8 flex flex-wrap gap-2">{trainingCategories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full border px-4 py-2 text-sm font-medium transition-colors ${category === item ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-background text-muted-foreground'}`}>{item} <span className="ml-1 opacity-60">{trainingByCategory(item).length}</span></button>)}</div><div key={category} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visibleTrainings.map((training, index) => <article key={`${training.category}-${training.name}`} className="group flex min-h-48 flex-col justify-between rounded-xl border border-border bg-background p-5"><div><div className="mb-8 flex items-center justify-between"><span className="text-xs text-muted-foreground">{String(index + 1).padStart(2, '0')}</span><ArrowUpRight size={17} className="text-muted-foreground" /></div>{training.name === 'K3 Listrik' ? <a href={`/${city.toLowerCase().replace(/\s+/g, '-').replace(/^kota-/, '')}/artikel/k3-listrik`} className="font-medium underline-offset-4 hover:underline">{training.category === 'Pelatihan' ? 'Training ' : ''}{trainingForCity(training.name, serviceLocation)}</a> : <h3 className="font-medium">{training.category === 'Pelatihan' ? 'Training ' : ''}{trainingForCity(training.name, serviceLocation)}</h3>}<p className="mt-2 text-sm leading-6 text-muted-foreground">{training.description}</p></div><a href={whatsappLink(`Halo, saya ingin bertanya tentang ${training.name} di ${city}.`)} target="_blank" rel="noreferrer" className="mt-5 text-xs font-medium underline underline-offset-4">Tanya via WhatsApp</a></article>)}</div></div></section>

    <section className="border-b border-border px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Pertanyaan umum" title="Punya pertanyaan? Kami siap membantu." /><div className="divide-y divide-border border-y border-border">{faqs.map(([question, answer], index) => <div key={question}><button onClick={() => setActiveFaq(activeFaq === index ? null : index)} className="flex w-full items-center justify-between gap-5 py-5 text-left text-sm font-medium"><span>{question}</span><ChevronDown size={18} className={`shrink-0 transition-transform ${activeFaq === index ? 'rotate-180' : ''}`} /></button>{activeFaq === index && <p className="max-w-2xl pb-5 pr-8 text-sm leading-6 text-muted-foreground">{answer}</p>}</div>)}</div></div></section>

    <section id="kontak" className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Area layanan" title={`Pelatihan K3 di ${serviceLocation} dan sekitarnya.`} description={`Kami melayani kebutuhan pelatihan dan sertifikasi K3 untuk perusahaan, proyek, dan individu di ${city}.`} /><div className="grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><div className="min-h-72 overflow-hidden rounded-xl border border-border bg-secondary"><iframe title={`Peta lokasi layanan ${city}`} src={`https://www.google.com/maps?q=Training+Sertifikasi+${encodeURIComponent(city)}&output=embed`} className="h-full min-h-72 w-full border-0 grayscale" loading="lazy" /></div><div className="rounded-xl border border-border p-6 sm:p-8"><MapPin size={21} /><p className="mt-12 text-sm text-muted-foreground">Area layanan</p><p className="mt-2 text-xl font-medium">{city} dan sekitarnya</p><div className="my-7 border-t border-border" /><p className="text-sm text-muted-foreground">Alamat kantor/perwakilan</p><p className="mt-2 text-sm leading-6">Hubungi kami via WhatsApp untuk informasi lokasi dan jadwal.</p><a href={whatsappLink()} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 text-sm font-medium underline underline-offset-4">Tanyakan jadwal <ArrowUpRight size={15} /></a></div></div></div></section>

    <footer className="border-t border-border bg-primary px-5 py-12 text-primary-foreground sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-2 lg:grid-cols-[1.4fr_0.6fr_0.8fr]"><div><div className="flex items-center gap-2 font-semibold"><span className="flex size-8 items-center justify-center rounded-md border border-primary-foreground/30"><HardHat size={17} /></span>Training Sertifikasi</div><p className="mt-5 max-w-sm text-sm leading-6 text-primary-foreground/60">Partner pelatihan dan sertifikasi K3 untuk membangun tempat kerja yang lebih aman di {city}.</p></div><div><p className="text-sm font-medium">Navigasi</p><div className="mt-5 flex flex-col gap-3 text-sm text-primary-foreground/60"><a href="#beranda">Beranda</a><a href="#pelatihan">Pelatihan</a><a href="#kontak">Kontak</a></div></div><div><p className="text-sm font-medium">Hubungi kami</p><a href={whatsappLink()} target="_blank" rel="noreferrer" className="mt-5 block text-sm text-primary-foreground/60">{PHONE_DISPLAY}</a><p className="mt-2 text-sm text-primary-foreground/60">WhatsApp untuk {city}</p></div></div></footer><a href={whatsappLink()} target="_blank" rel="noreferrer" aria-label={`Chat WhatsApp ${city}`} className="fixed bottom-5 right-5 z-40 flex size-14 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-lg sm:bottom-7 sm:right-7"><MessageCircle size={24} /></a>
  </main>
}
